# Earlier param files take precedence over later ones if there are duplicate
# parameters.
- ./network/layers.yml
- ./network/base/layers.yml
- ./network/base/populations.yml
- ./network/base/recorders.yml
- ./network/base/connections.yml
- ./network/base/connection_models.yml
- ./network/base/synapse_models.yml
- ./network/base/neuron_models.yml
- ./sessions/sessions_df.yml
- ./kernel/kernel_params.yml
- ./simulation/simulation_params.yml
