# Earlier param files take precedence over later ones if there are duplicate
# parameters.
- ./network/layers.yml
- ./network/synapse_models.yml
- ./network/neuron_models.yml
- ./network/connections.yml
- ./network/connection_models.yml
- ./simulation/recorders.yml
- ./simulation/sessions.yml
- ./simulation/kernel_params.yml
- ./simulation/simulation_params.yml
