# Earlier param files take precedence over later ones if there are duplicate
# parameters.

# Net
- ./layers.yml
- ./base/layers.yml
- ./base/populations.yml
- ./base/connections_singleconn.yml
- ./base/connection_models.yml
- ./base/recorder_models.yml
- ./base/synapse_models.yml
- ./base/neuron_models.yml
# NEST default params
- ./nest_defaults.yml
# Sessions
- ./sessions.yml
# Kernel
- ./kernel_params.yml
# Simulation
- ./simulation_params.yml
