/*
 *  rotatedrectangularmaskmodule.cpp
 *
 */

#include "rotatedrectangularmaskmodule.h"

// Generated includes:
#include "config.h"

// include headers with your own stuff
#include "rotatedrectangularmask.h"

// Includes from nestkernel:
#include "connection_manager_impl.h"
#include "connector_model_impl.h"
#include "dynamicloader.h"
#include "exceptions.h"
#include "genericmodel.h"
#include "genericmodel_impl.h"
#include "kernel_manager.h"
#include "model.h"
#include "model_manager_impl.h"
#include "nestmodule.h"
#include "target_identifier.h"

// Includes from sli:
#include "booldatum.h"
#include "integerdatum.h"
#include "sliexceptions.h"
#include "tokenarray.h"

// -- Interface to dynamic module loader ---------------------------------------

/*
 * There are three scenarios, in which RotatedRectangularMaskModule can be loaded by NEST:
 *
 * 1) When loading your module with `Install`, the dynamic module loader must
 * be able to find your module. You make the module known to the loader by
 * defining an instance of your module class in global scope. (LTX_MODULE is
 * defined) This instance must have the name
 *
 * <modulename>_LTX_mod
 *
 * The dynamicloader can then load modulename and search for symbol "mod" in it.
 *
 * 2) When you link the library dynamically with NEST during compilation, a new
 * object has to be created. In the constructor the DynamicLoaderModule will
 * register your module. (LINKED_MODULE is defined)
 *
 * 3) When you link the library statically with NEST during compilation, the
 * registration will take place in the file `static_modules.h`, which is
 * generated by cmake.
 */
#if defined( LTX_MODULE ) | defined( LINKED_MODULE )
spiking_visnet::RotatedRectangularMaskModule rotatedrectangularmaskmodule_LTX_mod;
#endif
// -- DynModule functions ------------------------------------------------------

spiking_visnet::RotatedRectangularMaskModule::RotatedRectangularMaskModule()
{
#ifdef LINKED_MODULE
  // register this module at the dynamic loader
  // this is needed to allow for linking in this module at compile time
  // all registered modules will be initialized by the main app's dynamic loader
  nest::DynamicLoaderModule::registerLinkedModule( this );
#endif
}

spiking_visnet::RotatedRectangularMaskModule::~RotatedRectangularMaskModule()
{
}

const std::string
spiking_visnet::RotatedRectangularMaskModule::name( void ) const
{
  return std::string( "Rotated Rectangular Mask Module" ); // Return name of the module
}

const std::string
spiking_visnet::RotatedRectangularMaskModule::commandstring( void ) const
{
  // Instruct the interpreter to load rotatedrectangularmaskmodule-init.sli
  return std::string( "(rotatedrectangularmaskmodule-init) run" );
}

//-------------------------------------------------------------------------------------

void
spiking_visnet::RotatedRectangularMaskModule::init( SLIInterpreter* i )
{
  nest::TopologyModule::register_mask<RotatedRectangularMask>("rotated_rectangular");
} // RotatedRectangularMaskModule::init()
